[package]
edition.workspace = true
name              = "fast-lexer"
version           = "0.1.0"

[dependencies]
logos = "0.16.1"
memchr = "2.8.0"

[lints]
workspace = true

[dev-dependencies]
criterion   = "0.8.2"
divan       = "0.1.21"
expect-test = "1.5.1"

[[bench]]
harness = false
name    = "lexers"
